version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: smartagri_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./ml:/ml  # folder sa ML modelom
    working_dir: /app
    command: python app.py
    networks:
      - smartagri_net

  frontend:
    build:
      context: ./frontend
    container_name: smartagri_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - smartagri_net

networks:
  smartagri_net:
    driver: bridge


